repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.6  # or the version you want
  hooks:
  - id: clang-format
    args:
    - -style=file
    - -i

- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-tidy
    args:
    - -fix-errors
    - -fix

fail_fast: false

