cc_test(
    name = "classfile_loader_test",
    srcs = ["ClassFileLoaderUT.cpp"],
    deps = [
        "//classfile_loader",
        "//classfile",
        "@gtest//:gtest_main",
        "@bazel_tools//tools/cpp/runfiles"
    ],
    data = ["//resources"]
)
