cc_binary(
    name = "classfile_loader_test_manual",
    srcs = ["ClassFileLoaderUT.cpp"],
    deps = [
        "//classfile_loader",
        "//classfile",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    data = ["//resources"],
)
