cc_test(
    name = "class_loader_test",
    srcs = ["ClassLoaderUT.cpp"],
    deps = [
        "//class_loader",
        "//class",
        "@gtest//:gtest_main",
        "@bazel_tools//tools/cpp/runfiles"
    ],
    data = ["//resources"]
)
